### ISSUE TITLE
:hover and pseudo elements in vnode style

### ISSUE THREAD

**Issue by staltz** [Matt-Esch/virtual-dom#179]
I'm building an app with virtual-dom, and going 100% styles in JavaScript rather than in CSS.

How do I express `:hover` state and `:before`/`:after` pseudo elements in virtual-hyperscript?

For instance

```css
.thing > a {
  color: #FF0000;
  &:hover {
    color: #FF00FF;
  }
  &:hover:after {
    content: "\276F";
    display: inline-block;
    position: absolute;
    right: 5px;
  }
}
```
